---
# \
## > BuilderTools configuration file
# /

# Do not change this!
config-version: 1.2.0

schematics:
  # Available modes: startup, oncommand
  #  - startup - when plugin starts, all schematics will loaded
  #  - oncommand - schematics will been loaded when player use '//schem load' command
  load: startup
...