--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CzechPMDevs/BuilderTools
branches:
- master
- 1.1.0
- 1.2.0
projects:
  BuilderTools:
    path: BuilderTools/
    icon: "icon.png"
...
