---
# BuilderTools configuration file
# Target BuilderTools version: 1.2.0-beta3

# Do not change this line.
config-version: 1.2.0.1

# This is format which will be used for creating schematics
# Supported formats: 'mcedit', 'mcstructure'
output-schematics-format: 'mcedit'

# PowerItems settings:
items:
  wand-axe:
    enabled: true
    name: "§r§fWand Axe\n§7§oBreak for first pos\n§7§oTouch for second pos"
  blockinfo-stick:
    enabled: false
    name: "§r§fDebug Stick\n§7§oTouch block for info"
...